// icons are taken from https://mapicons.mapsmarker.com/
export enum PlaceCategory {
    Default = 'star',
    Airport = 'airport',
    Archaeology = 'archaeology',
    Art = 'art',
    Beach = 'beach',
    Campfire = 'campfire',
    Cave = 'cave',
    Cemetery = 'cemetary',
    City = 'bigcity',
    CityPart = 'citypart',
    CitySquare = 'citysquare',
    Cottage = 'cottage',
    Bridge = 'bridge',
    Building = 'building',
    Castle = 'castle',
    Church = 'church',
    Dam = 'dam',
    Hut = 'hut',
    Nature = 'forest',
    Farm = 'farm',
    Fortress = 'fortification',
    Harbor = 'harbor',
    Hospital = 'hospital',
    Hotel = 'hotel',
    Industry = 'industry',
    Island = 'island',
    Library = 'library',
    Lighthouse = 'lighthouse',
    Manor = 'manor',
    Memorial = 'memorial',
    Military = 'military',
    Mine = 'mine',
    MineClosed = 'mine-closed',
    Motorway = 'motorway',
    Mountain = 'mountain',
    Museum = 'museum',
    Park = 'park',
    Petroglyphs = 'petroglyphs',
    Prison = 'prison',
    Restaurant = 'restaurant',
    Road = 'road',
    River = 'river',
    Ruins = 'ruins',
    SmallCity = 'smallcity',
    School = 'school',
    Sports = 'sports',
    Station = 'station',
    Store = 'store',
    Street = 'street',
    Theater = 'theater',
    TouristVillage = 'touristvillage',
    Trail = 'trail',
    Trailhead = 'trailhead',
    Tree = 'tree',
    University = 'university',
    War = 'war',
    Waterfall = 'waterfall',
    Watertower = 'watertower',
    Stop = 'stop',
}

export const PLACE_CATEGORY_DESCRIPTIONS: {[category in PlaceCategory]: string} = {
    [PlaceCategory.Default]: 'Any place of interest not covered by other categories',
    [PlaceCategory.Airport]: 'Airport',
    [PlaceCategory.Archaeology]: 'Historical sight, unless covered by more specific categories',
    [PlaceCategory.Art]: 'Art museum/gallery/similar',
    [PlaceCategory.Campfire]: 'Campfire-spot, lean-to, other non-enclosed wilderness shelter',
    [PlaceCategory.Cave]: 'Cave, tunnel',
    [PlaceCategory.Cottage]: 'Cottage, summer house, rental or otherwise',
    [PlaceCategory.Cemetery]: 'Cemetery',
    [PlaceCategory.City]: 'City (not legally, but settlement which would commonly be considered as city-like)',
    [PlaceCategory.CityPart]: 'City subdivision, unless completely suburban or rural in character',
    [PlaceCategory.CitySquare]: 'Square',
    [PlaceCategory.Beach]: 'Beach',
    [PlaceCategory.Bridge]: 'Bridge',
    [PlaceCategory.Building]: 'Notable building not covered by other categories',
    [PlaceCategory.Castle]: 'Castle or palace, possibly ruined',
    [PlaceCategory.Church]: 'Church or other religious building',
    [PlaceCategory.Dam]: 'Dam',
    [PlaceCategory.Hut]: 'Wilderness hut of any type (unstaffed), other enclosed wilderness shelter',
    [PlaceCategory.Nature]: 'Major protected nature area',
    [PlaceCategory.Farm]: 'Farm or other agricultural location, unless an old manor',
    [PlaceCategory.Fortress]: 'Fortifications (unless they can be called a castle)',
    [PlaceCategory.Harbor]: 'Harbor of any size and kind',
    [PlaceCategory.Hospital]: 'Active healthcare facility of any kind',
    [PlaceCategory.Hotel]: 'Hotel, hostel',
    [PlaceCategory.Industry]: 'Industrial facility, whether active or historical',
    [PlaceCategory.Island]: 'Island',
    [PlaceCategory.Library]: 'Library',
    [PlaceCategory.Lighthouse]: 'Lighthouse or a similar navigation sign',
    [PlaceCategory.Manor]: 'Manor',
    [PlaceCategory.Memorial]: 'Memorial, unless in connection with some other place of interest',
    [PlaceCategory.Military]: 'Active military installation',
    [PlaceCategory.Mine]: 'Active mine',
    [PlaceCategory.MineClosed]: 'Disused mine',
    [PlaceCategory.Motorway]: 'Motorway or motorway-quality road',
    [PlaceCategory.Mountain]: 'Mountain or other prominence, massif',
    [PlaceCategory.Museum]: 'Museum, unless covered by more specific categories',
    [PlaceCategory.Park]: 'Urban park',
    [PlaceCategory.Petroglyphs]: 'Rock paintings or drawings',
    [PlaceCategory.Prison]: 'Prison',
    [PlaceCategory.Restaurant]: 'Restaurant, cafe, bar, any kind',
    [PlaceCategory.River]: 'Water body, any kind',
    [PlaceCategory.Ruins]: 'Ruins, if sufficiently destroyed that no other category will be appropriate',
    [PlaceCategory.Road]: 'Road, unless a motorway',
    [PlaceCategory.School]: 'School, other education institution up to secondary school',
    [PlaceCategory.SmallCity]: 'Village (not legally, but settlement which would NOT be normally considered city-like)',
    [PlaceCategory.Sports]: 'Stadium, any other sports facility',
    [PlaceCategory.Station]: 'Railway station',
    [PlaceCategory.Street]: 'City street',
    [PlaceCategory.Store]: 'Store of any kind or shopping center',
    [PlaceCategory.Theater]: 'Theater',
    [PlaceCategory.Trailhead]: 'Trailhead, entrance to a hiking area, normally with a parking lot',
    [PlaceCategory.Tree]: 'Minor protected nature area or other nature sight not covered by other categories',
    [PlaceCategory.TouristVillage]: 'Camping, minor settlement that is specifically meant for tourists',
    [PlaceCategory.Trail]: 'Hiking trail, if it makes sense to describe one separately from nature sights',
    [PlaceCategory.University]: 'University, research facility, other higher or professional education institution',
    [PlaceCategory.War]: 'Historical battlefields, other war monuments and historical military areas',
    [PlaceCategory.Waterfall]: 'Waterfall or significant rapids',
    [PlaceCategory.Watertower]: 'Water tower',
    [PlaceCategory.Stop]: 'Something intentionally NOT explored',
};

export const PLACE_CATEGORY_SEARCH_STRINGS: {[category in PlaceCategory]: string[]} = {
    [PlaceCategory.Default]: ['default'],
    [PlaceCategory.Airport]: ['airport'],
    [PlaceCategory.Archaeology]: ['archaeology', 'history'],
    [PlaceCategory.Art]: ['art', 'museum', 'gallery'],
    [PlaceCategory.Campfire]: ['campfire', 'lean-to', 'leanto', 'laavu', 'shelter'],
    [PlaceCategory.Cave]: ['cave', 'tunnel'],
    [PlaceCategory.Cottage]: ['cottage', 'summer house'],
    [PlaceCategory.Cemetery]: ['cemetery', 'graveyard'],
    [PlaceCategory.City]: ['city', 'town'],
    [PlaceCategory.CityPart]: ['area', 'city area', 'city part'],
    [PlaceCategory.CitySquare]: ['square', 'tori'],
    [PlaceCategory.Beach]: ['beach'],
    [PlaceCategory.Bridge]: ['bridge'],
    [PlaceCategory.Building]: ['building', 'house'],
    [PlaceCategory.Castle]: ['castle', 'palace'],
    [PlaceCategory.Church]: ['church', 'cathedral', 'chapel'],
    [PlaceCategory.Dam]: ['dam', 'hydro'],
    [PlaceCategory.Hut]: ['hut', 'wilderness hut', 'shelter'],
    [PlaceCategory.Nature]: ['national park', 'nature', 'protected nature area'],
    [PlaceCategory.Farm]: ['farm'],
    [PlaceCategory.Fortress]: ['fortress', 'fortifications'],
    [PlaceCategory.Harbor]: ['harbor', 'harbour', 'port'],
    [PlaceCategory.Hospital]: ['hospital', 'health'],
    [PlaceCategory.Hotel]: ['hotel', 'hostel'],
    [PlaceCategory.Industry]: ['industry', 'factory', 'plant'],
    [PlaceCategory.Island]: ['island'],
    [PlaceCategory.Library]: ['library'],
    [PlaceCategory.Lighthouse]: ['lighthouse', 'beacon'],
    [PlaceCategory.Manor]: ['manor'],
    [PlaceCategory.Memorial]: ['memorial', 'monument'],
    [PlaceCategory.Military]: ['military', 'army', 'navy'],
    [PlaceCategory.Mine]: ['mine'],
    [PlaceCategory.MineClosed]: ['mine'],
    [PlaceCategory.Motorway]: ['motorway', 'highway'],
    [PlaceCategory.Mountain]: ['mountain', 'hill', 'fell', 'massif'],
    [PlaceCategory.Museum]: ['museum'],
    [PlaceCategory.Park]: ['park'],
    [PlaceCategory.Petroglyphs]: ['rock painting', 'rock drawing'],
    [PlaceCategory.Prison]: ['prison'],
    [PlaceCategory.Restaurant]: ['restaurant', 'cafe', 'bar'],
    [PlaceCategory.River]: ['river', 'water', 'lake', 'sea', 'bay', 'strait', 'inlet'],
    [PlaceCategory.Ruins]: ['ruins'],
    [PlaceCategory.Road]: ['road'],
    [PlaceCategory.School]: ['school', 'kindergarten', 'high school'],
    [PlaceCategory.SmallCity]: ['village', 'town', 'hamlet'],
    [PlaceCategory.Sports]: ['stadium', 'sports'],
    [PlaceCategory.Station]: ['railroad', 'railway', 'station'],
    [PlaceCategory.Street]: ['street'],
    [PlaceCategory.Store]: ['store', 'supermarket', 'mall', 'shopping'],
    [PlaceCategory.Theater]: ['theater'],
    [PlaceCategory.Trailhead]: ['trail', 'trailhead', 'parking'],
    [PlaceCategory.Tree]: ['tree', 'nature', 'protected nature area'],
    [PlaceCategory.TouristVillage]: ['camping', 'tourist village'],
    [PlaceCategory.Trail]: ['trail'],
    [PlaceCategory.University]: ['university', 'research', 'institute'],
    [PlaceCategory.War]: ['war', 'battlefield', 'military'],
    [PlaceCategory.Waterfall]: ['waterfall', 'rapids'],
    [PlaceCategory.Watertower]: ['water tower'],
    [PlaceCategory.Stop]: ['stop']
};
