<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>default</LangVersion>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AngleSharp" Version="1.8.3" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
        <PackageReference Include="Microsoft.Playwright" Version="1.63.0" />
        <PackageReference Include="xunit.v3" Version="4.0.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fennica3\Fennica3.csproj" />
        <ProjectReference Include="..\KoTi\KoTi.csproj" />
        <ProjectReference Include="..\Holvi\Holvi.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>
