// <auto-generated />
using System;
using Holvi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Holvi.Migrations
{
    [DbContext(typeof(HolviDbContext))]
    [Migration("20260122210615_PlaceLocalizationsMetaNullable")]
    partial class PlaceLocalizationsMetaNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Holvi.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentMD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Draft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Holvi.Models.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Camera")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Lat")
                        .HasColumnType("REAL");

                    b.Property<string>("Lens")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Lng")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("PhotographedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website1xUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website2xUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WebsiteSizesExist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("IsPrivate");

                    b.HasIndex("PhotographedAt");

                    b.HasIndex("PlaceId");

                    b.HasIndex("Rating");

                    b.HasIndex("SetId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("Holvi.Models.PictureSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("PictureSets");
                });

            modelBuilder.Entity("Holvi.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentMD")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Draft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExploreStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<string>("Links")
                        .HasColumnType("TEXT");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TitleImageOffsetY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TitlePictureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Zoom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Draft");

                    b.HasIndex("ExploreStatus");

                    b.HasIndex("Icon");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("Rating");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("Holvi.Models.PlaceLocalization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentMD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Draft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("PlaceLocalizations");
                });

            modelBuilder.Entity("Holvi.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentMD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Draft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationDescription")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Mini")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicTransport")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleImageCaption")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("TitleImageInText")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TitleImageOffsetY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TitlePictureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Twitter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TitlePictureId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Holvi.Models.Redirect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UrlFrom")
                        .IsUnique();

                    b.ToTable("Redirects");
                });

            modelBuilder.Entity("Holvi.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PictureTag", b =>
                {
                    b.Property<int>("PicturesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PicturesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PictureTag");
                });

            modelBuilder.Entity("PlaceTag", b =>
                {
                    b.Property<int>("PlacesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlacesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PlaceTag");
                });

            modelBuilder.Entity("Holvi.Models.Picture", b =>
                {
                    b.HasOne("Holvi.Models.Place", "Place")
                        .WithMany("Pictures")
                        .HasForeignKey("PlaceId");

                    b.HasOne("Holvi.Models.PictureSet", "Set")
                        .WithMany("Pictures")
                        .HasForeignKey("SetId");

                    b.Navigation("Place");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Holvi.Models.PictureSet", b =>
                {
                    b.HasOne("Holvi.Models.PictureSet", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Holvi.Models.Place", b =>
                {
                    b.HasOne("Holvi.Models.Place", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.OwnsOne("Holvi.Models.PlaceMeta", "Meta", b1 =>
                        {
                            b1.Property<int>("PlaceId");

                            b1.Property<string>("Directions");

                            b1.Property<string>("FlagEmoji");

                            b1.Property<string>("MapType");

                            b1.Property<string>("PublicTransport");

                            b1.Property<string>("Season");

                            b1.HasKey("PlaceId");

                            b1.ToTable("Places");

                            b1
                                .ToJson("Meta")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("PlaceId");
                        });

                    b.Navigation("Meta");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Holvi.Models.PlaceLocalization", b =>
                {
                    b.HasOne("Holvi.Models.Place", "Place")
                        .WithMany("Localizations")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Holvi.Models.PlaceMeta", "Meta", b1 =>
                        {
                            b1.Property<int>("PlaceLocalizationId");

                            b1.Property<string>("Directions");

                            b1.Property<string>("FlagEmoji");

                            b1.Property<string>("MapType");

                            b1.Property<string>("PublicTransport");

                            b1.Property<string>("Season");

                            b1.HasKey("PlaceLocalizationId");

                            b1.ToTable("PlaceLocalizations");

                            b1
                                .ToJson("Meta")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("PlaceLocalizationId");
                        });

                    b.Navigation("Meta")
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Holvi.Models.Post", b =>
                {
                    b.HasOne("Holvi.Models.Picture", "TitlePicture")
                        .WithMany()
                        .HasForeignKey("TitlePictureId");

                    b.OwnsMany("Holvi.Models.Post+CoatOfArms", "CoatsOfArms", b1 =>
                        {
                            b1.Property<int>("PostId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int?>("Size");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("PostId", "__synthesizedOrdinal");

                            b1.ToTable("Posts");

                            b1
                                .ToJson("CoatsOfArms")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.OwnsMany("Holvi.Models.Post+GeoPoint", "Geo", b1 =>
                        {
                            b1.Property<int>("PostId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Anchor");

                            b1.Property<string>("Description");

                            b1.Property<string>("Icon");

                            b1.Property<double>("Lat");

                            b1.Property<double>("Lng");

                            b1.PrimitiveCollection<string>("Maps");

                            b1.Property<string>("Subtitle");

                            b1.Property<string>("Title");

                            b1.Property<string>("TitleImage");

                            b1.Property<int?>("Zoom");

                            b1.HasKey("PostId", "__synthesizedOrdinal");

                            b1.ToTable("Posts");

                            b1
                                .ToJson("Geo")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.OwnsMany("Holvi.Models.Post+Link", "Links", b2 =>
                                {
                                    b2.Property<int>("GeoPointPostId");

                                    b2.Property<int>("GeoPoint__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Label")
                                        .IsRequired();

                                    b2.Property<string>("Path")
                                        .IsRequired();

                                    b2.HasKey("GeoPointPostId", "GeoPoint__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Posts");

                                    b2.WithOwner()
                                        .HasForeignKey("GeoPointPostId", "GeoPoint__synthesizedOrdinal");
                                });

                            b1.Navigation("Links");
                        });

                    b.Navigation("CoatsOfArms");

                    b.Navigation("Geo");

                    b.Navigation("TitlePicture");
                });

            modelBuilder.Entity("PictureTag", b =>
                {
                    b.HasOne("Holvi.Models.Picture", null)
                        .WithMany()
                        .HasForeignKey("PicturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holvi.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlaceTag", b =>
                {
                    b.HasOne("Holvi.Models.Place", null)
                        .WithMany()
                        .HasForeignKey("PlacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holvi.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Holvi.Models.PictureSet", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("Holvi.Models.Place", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Localizations");

                    b.Navigation("Pictures");
                });
#pragma warning restore 612, 618
        }
    }
}
