<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <UserSecretsId>b0a9d1e2-3a02-49e7-8b8f-157ca08fb5bf</UserSecretsId>
    <LangVersion>default</LangVersion>
    <AssemblyVersion>3.4.0</AssemblyVersion>
    <InformationalVersion>3.4.0</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Htmx" Version="1.12.0" />
    <PackageReference Include="Htmx.TagHelpers" Version="1.12.0" />
    <PackageReference Include="Markdig" Version="1.3.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\favicon.svg" />
    <None Include="wwwroot\koti-logo.svg" />
    <None Include="wwwroot\manifest.json" />
    <!-- Don't publish the frontend source files, but do show them in the project files list -->
    <Content Remove="Frontend\**" />
    <None Remove="Frontend\**" />
    <None Include="Frontend\**" Exclude="Frontend\node_modules\**" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\Fennica3\Fennica3.csproj" />
    <ProjectReference Include="..\Holvi\Holvi.csproj" />
  </ItemGroup>

  <Target Name="SetSourceRevisionId" BeforeTargets="InitializeSourceControlInformation">
    <Exec
      Command="echo -n `date +%Y%m%d-` ; git describe --long --always --dirty --exclude=* --abbrev=8"
      ConsoleToMSBuild="True"
      IgnoreExitCode="False"
    >
      <Output PropertyName="SourceRevisionId" TaskParameter="ConsoleOutput"/>
    </Exec>
  </Target>

  <Target Name="PublishRunBun" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <Exec WorkingDirectory="Frontend" Command="bun install" />
    <Exec WorkingDirectory="Frontend" Command="bun run build" />

    <!-- Include the newly-built files in the publish output -->
    <ItemGroup>
      <DistFiles Include="wwwroot\frontend\**" />
    </ItemGroup>
  </Target>


  <!-- https://github.com/dotnet/sdk/issues/22716#issuecomment-2276449122 -->
  <Target Name="DeleteAllAppsettings" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <AppSettingsFilesToDelete Include="$(OutputPath)appsettings*.json" />
    </ItemGroup>
    <Delete Files="@(AppSettingsFilesToDelete)" />
    <Message Text="Deleted appsettings JSON files: @(AppSettingsFilesToDelete)" Importance="high" />
  </Target>
  <Target Name="CopyProjectAppSettings" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <AppSettingsJsonFiles Include="appsettings*.json" />
    </ItemGroup>
    <Copy SourceFiles="@(AppSettingsJsonFiles)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="false" />
    <Message Text="Copied project appsettings JSON files to output directory." Importance="high" />
  </Target>
</Project>
