export enum PlaceCategory {
    Default = 'star',
    Archaeology = 'archaeology',
    City = 'bigcity',
    Bridge = 'bridge',
    Castle = 'castle',
    Church = 'church',
    Dam = 'dam',
    Nature = 'forest',
    Fortress = 'fortification',
    Industry = 'industry',
    Island = 'island',
    Lighthouse = 'lighthouse',
    Memorial = 'memorial',
    Mountain = 'mountain',
    Museum = 'museum',
    Petroglyphs = 'petroglyphs',
    River = 'river',
    SmallCity = 'smallcity',
    Station = 'station',
    Stop = 'stop',
    TouristVillage = 'touristvillage',
    Trail = 'trail',
    Tree = 'tree',
    War = 'war',
    Waterfall = 'waterfall'
}

export const PLACE_CATEGORY_DESCRIPTIONS: {[category in PlaceCategory]: string} = {
    [PlaceCategory.Default]: 'Any place of interest not covered by other categories',
    [PlaceCategory.Archaeology]: 'Historical sight, unless covered by more specific categories',
    [PlaceCategory.City]: 'City (not legally, but settlement which would commonly be considered as city-like)',
    [PlaceCategory.Bridge]: 'Bridge',
    [PlaceCategory.Castle]: 'Castle or palace, possibly ruined',
    [PlaceCategory.Church]: 'Church or other religious building',
    [PlaceCategory.Dam]: 'Dam',
    [PlaceCategory.Nature]: 'Major protected nature area',
    [PlaceCategory.Fortress]: 'Fortifications (unless they can be called a castle',
    [PlaceCategory.Industry]: 'Industrial facility, wheter active or historical',
    [PlaceCategory.Island]: 'Island',
    [PlaceCategory.Lighthouse]: 'Lighthouse or a similar navigation sign',
    [PlaceCategory.Memorial]: 'Memorial, unless in connection with some other place of interest',
    [PlaceCategory.Mountain]: 'Mountain or other prominence, massif',
    [PlaceCategory.Museum]: 'Museum, unless covered by more specific categories',
    [PlaceCategory.Petroglyphs]: 'Rock paintings or drawings',
    [PlaceCategory.River]: 'Water body, any kind',
    [PlaceCategory.SmallCity]: 'Village (not legally, but settlement which would NOT be normally considered city-like)',
    [PlaceCategory.Station]: 'Railway station',
    [PlaceCategory.Stop]: 'Something intentionally NOT explored',
    [PlaceCategory.Tree]: 'Minor protected nature area or other nature sight not covered by other categories',
    [PlaceCategory.TouristVillage]: 'Camping, hotel, minor settlement that is specifically meant for tourists',
    [PlaceCategory.Trail]: 'Hiking trail, if it makes sense to describe one separately from nature sights',
    [PlaceCategory.War]: 'Historical battlefields, other war monuments',
    [PlaceCategory.Waterfall]: 'Waterfall or significant rapids'
};
